import type { NextPage } from "next";
import Head from "next/head";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";
import Box from "@mui/material/Box";

import Navbar from "../components/layout/Navbar.component";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Shopping MA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <Container>
                <Grid container spacing={2} sx={{ mt: 4 }}>
                    <Grid item sm={2} xs={12}>
                        <List
                            component="nav"
                            sx={{ width: "100%", bgcolor: "background.paper" }}
                            aria-labelledby="categories-list"
                            subheader={
                                <ListSubheader
                                    component="div"
                                    id="categories-list"
                                >
                                    Categories
                                </ListSubheader>
                            }
                        >
                            <ListItem>
                                <ListItemText primary="Categories" />
                            </ListItem>
                        </List>
                    </Grid>
                    <Grid item sm={8} xs={12}>
                        Promotions
                    </Grid>
                    <Grid item sm={2} xs={12}>
                        Other
                    </Grid>
                </Grid>
            </Container>
        </div>
    );
};

export default Home;
